image python:3-alpine

stages:
  - build
  - deploy

before_script:
  - apt update && apt install gettext-base


###################
# Build
###################
build-package:
  stage: build
  variables:
    VERSION: build
  script:
    - envsubst '${VERSION}' < setup.py > setup.py.new
    - mv setup.py.new setup.py
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*
    expire_in: 1 day


###################
# Deploy
###################
deploy-package:
  stage: deploy
  script:
    - VERSION=$(echo ${CI_COMMIT_REF_NAME} | sed "s/v//")
    - export VERSION=$VERSION
    - envsubst '${VERSION}' < setup.py > setup.py.new
    - mv setup.py.new setup.py
    - echo -e "$PYPI" > ~/.pypirc
    - pip install twine
    - twine upload dist/* -r pypi
  only:
    - tags