image: python:3-alpine

stages:
  - tests
  - build
  - deploy

.set_version: &set_version |
  apk --no-cache add gettext
  VERSION=$(echo ${CI_COMMIT_REF_NAME} | sed "s/v//")
  export VERSION=$VERSION
  envsubst '${VERSION}' < setup.py > setup.py.new
  mv setup.py.new setup.py


###################
# Tests
###################
unit-tests:
  stage: tests
  script:
    - pip3 install -r requirements.txt
    - python3 -m unittest


###################
# Build
###################
build-package:
  stage: build
  script:
    - *set_version
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*
    expire_in: 1 day
  only:
    - master
    - tags


###################
# Deploy
###################
deploy-package:
  stage: deploy
  script:
    - *set_version
    - echo -e "$PYPI" > ~/.pypirc
    - apk add --no-cache gcc musl-dev libffi-dev openssl-dev
    - pip install twine
    - twine upload dist/* -r pypi
  only:
    - tags